### ISSUE TITLE
Cache directory randomly inaccessible due to  permissions in Windows

### ISSUE THREAD

**Issue by mostlyhuman** [lando/symfony#46]
Hello there, I am not changing any permissions so I am not sure why Icaros keeps losing access rights.  Can you tell me exactly which permissions Icaros requires the folder to have? Perhaps that will help me explore the issue further.  One thing to note, when this happens Icaros cant fix the permissions right away, but then later i can try again and suddenly it can, very strange.

**Comment by reynoldsalec** [comment]
Hey @mostlyhuman, to my knowledge Lando isn't using Icaros for anything. Could you show me an example of the error you're seeing?

Also curious what version of Windows you're on and if you're running Lando in WSL2.

**Comment by reynoldsalec** [comment]
It's possible if you're on an old computer you're experiencing a race condition with permission sweeping that could cause problems...unfortunately that won't get resolved until the rearchitecture in Lando v4 is released.

**Comment by mostlyhuman** [comment]
I figured out it had something to do with OneDrive, it would have the same
behavior no matter which OneDrive monitored directory/folder I tried but it
works fine in unmonitored directories.

**Comment by mostlyhuman** [comment]
it's just that standard error where next to the thumbnail cache path it shows like a red triangle and it says you can click the red triangle to try to have Icaros set the permissions and then when it tries it says it couldn't do it because of a running process or something along those lines

**Comment by reynoldsalec** [comment]
Gotcha, sounds pretty specific to your conditions so I'll close this out unless you had any followups, thanks @mostlyhuman!
